items = {
    "ray gun": {
        "description": "Don't use without adult supervision!",
        "type": "weapon",
        "damage": 10,
        "value": 75,
    },
    "titanium bar": {
        "description": "An ingot of very strong metal.",
        "type": "material",
        "damage": 1,
        "value": 25,
    },
    "watermelon":{
        "description": "A green and red melon.",
        "type": "consumable",
        "damage": 15,
        "value": 150,
        "upStat": "hp",
        "upAmount": 200,
        },
    "ration":{
        "description": "A typical food ration, not very tasty.",
        "type": "consumable",
        "damage": 1,
        "value": 5,
        "upStat": "hp",
        "upAmount": 8,
    },
    "xp booster":{
        "description": "A strange serum injection that makes one feel more experienced.",
        "type": "consumable",
        "damage": 1,
        "value": 150,
        "upStat": "xp",
        "upAmount": 50,
    }, 
    "speedstim":{
        "description": "A strange serum injection that makes one feel faster.",
        "type": "consumable",
        "damage": 1,
        "value": 10,
        "upStat": "spd",
        "upAmount": 2,
    },
}
