rooms = {
    "Hub 1 Center": {
        "description": "You are standing on on a dirt road intersection.  There is a large town around you.  To your left, a small cart sells melons.",
        "exits": {"west": "Road 1", "east": "Road 2", "south": "South Road 1"},
        "items": [],
        "tools": [],
        "npcs": ["melon shop 1"],
        "entities": {"guard":{"hp":2,"atk":2,"def":2,"spd":10,"name": "Guard"}},
    },
    "Road 1": {
        "description": "You're standing on a dirt road.  There is a small hab on the left side of the road and a small arms shop on the other.",
        "exits": {"east": "Hub 1 Center", "north": "Arms Shop 1", "south": "Small Hab 1"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "Arms Shop 1": {
        "description": "You're standing in a dusty arms shop.  There are a few weapons and armor plates for sale.",
        "exits": {"out": "Road 1"},
        "items":[],
        "tools":[],
        "npcs": ["arms shop 1"],
        "entities": {},
    },
    "Road 2": {
        "description": "You're standing on a dirt road.",
        "exits": {"west": "Hub 1 Center", "east": "Road 3", "north": "MedShop 1"},
        "items":[],
        "tools":[],
        "npcs": ["jordan harrison"],
        "entities": {},
    },
    "MedShop 1": {
        "description": "You're in a dusty MedShop selling all sorts of medications.",
        "exits": {"south": "Road 2"},
        "items":[],
        "tools":[],
        "npcs": ["medshop 1"],
        "entities": {},
    },
    "Road 3": {
        "description": "You're standing on a dirt road.",
        "exits": {"west": "Road 2", "east": "Road 4"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "Road 4": {
        "description": "You're standing on a dirt road.",
        "exits": {"west": "Road 3", "north": "Road 5"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "Road 5": {
        "description": "You're standing on a dirt road.",
        "exits": {"south": "Road 5"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "South Road 1": {
        "description": "You're standing on a dirt road.",
        "exits": {"north": "Hub 1 Center", "south": "South Road 2"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "South Road 2": {
        "description": "You're standing on a dirt road.",
        "exits": {"north": "South Road 1", "east": "FoodMart 1", "south":"South Road 3"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "FoodMart 1": {
        "description": "You are in an oddly clean grocery store.  Everyone is has fake smiles plastered on their faces.",
        "exits": {"west": "South Road 2"},
        "items":[],
        "tools":[],
        "npcs": ["foodmart 1"],
        "entities": {},
    },
    "South Road 3": {
        "description": "You're standing on a dirt road.",
        "exits": {"north": "South Road 2", "south": "South Gate 1", "east": "South West Road 1"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "South West Road 1": {
        "description": "You're standing on a dirt road.",
        "exits": {"west": "South Road 3", "east": "South West Road 2", "south": "Small Hab 2"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
    "Small Hab 2": {
        "description": "You're in an abandoned hab.  It appears as though it could be fixed up.",
        "exits": {"west": "South Road 3", "east": "South West Road 2", "south": "Small Hab 2"},
        "items":[],
        "tools":[],
        "npcs": [],
        "entities": {},
    },
}
